### PR TITLE
Add wrapping CSS for item request URLs

### PR DESCRIPTION
**Pull request by jajanet**
Suggestion implementation for enhancement cseg-michigan#346, implemented based on how style is added for individual items for this file and other similar files.

### CODE REVIEW

**Comment by westbl** [comment]
@jajanet sorry for the late response; things have been hectic lately haha.  One thing I would like for you to add before I merge the PR is this same fix for the User page; you show the "Chez Betty User Admin" page in your screenshot, but the fix in this PR is only for the "Chez Betty Admin" page, which uses a different jinja2 file to generate the form.  Would you please update the code to reflect the same change but on the User side of things?

**Comment by jajanet** [comment]
@westbl yeah sure! I've been doing some tinkering around trying to figure this out, and I'm having trouble understanding what you mean by "User page." Could you elaborate?

**Comment by westbl** [comment]
@jajanet so the main thing to know about the Betty web interface is that there are a few different "views"; in this case the ones we are working with are the "admin" view and the "user" view.  Depending on your user type you will have access to one or both of these views, and the jinja2 and css pages are unique for each one.

As a non-administrator, you can only view the "user" side of things.  The file you modified for this PR was chezbetty/templates/admin/requests.jinja2, but that is an admin-view file; I _believe_ the file you modified for your initial screenshot is located at chezbetty/templates/user/item_request.jinja2.  I am fairly certain this is the case because your initial screenshot said "Chez Betty User Admin" at the top left of the navbar; if you were looking at the admin-side page it would have said "Chez Betty Admin".

Does this clear things up?

**Comment by jajanet** [comment]
@westbl Ah that makes perfect sense! I appreciate your patience and thorough explanation.

I think I added the appropriate changes and they should be reflected now in the pull request now; the rest of the templates appear to be okay as far as I can see as well.

Let me know if I should add anything!

**Comment by westbl** [comment]
@jajanet looks good to me!  Thanks for the help :)

**Pull request merged**
